## L119: Inferential Statistics Exercise

### Shoe Sales Data

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

We have sales data by shoe size from two years: 2015 and 2016.

In [37]:
usa15 = pd.read_csv('./data/shoes_2015.csv')
usa15

      US   1   2   3   4   5   6   7   8   9  10  11  12
0    6.0   0   0   0   0   3   1   1   3   5   4   0   0
1    6.5   4   1   0   1   0   0   2   3   0   1   3   3
2    7.0   0   0   0   0   1   2   1   0   1   2   2   3
3    7.5   0   1   2   1   0   0   3   2   3   2   2   2
4    8.0   5   3   1   0   6   6   4   0   5   6   3   3
5    8.5   4   5   3   1   2  11   6   6   4  12   4   2
6    9.0  10  14   7   9  17  16  20  21  13  17  10  12
7    9.5  18  16  23  15  16  16  19  26  25  17  35  24
8   10.0   8  13  13  15   7  20  22  18  22  15  11  14
9   10.5   7  13   8   8  15  10  16   8  16  16  17  14
10  11.0   5   5   4   7   5   5   4   6   3   5   5  10
11  11.5   3   3   2   3   6   9   6   6   3   8   3   7
12  12.0   1   0   0   3   1   4   1   2   4   3   6   3
13  13.0   0   0   1   0   1   3   1   0   0   3   0   1
14  14.0   1   2   1   2   1   0   3   3   0   1   2   2
15  15.0   0   0   0   0   1   0   0   1   1   0   1   1
16  16.0   0   0   0   0   0   0   0   0   0   0   0   0

In [38]:
usa16 = pd.read_csv('./data/shoes_2016.csv')
usa16

      US   1   2   3   4   5   6   7   8   9  10  11  12
0    6.0   4   1   3   1   3   3   3   4   3   7   3   0
1    6.5   3   2   0   1   0   0   1   7   2   1   2   1
2    7.0   0   0   1   0   6   4   4   2   3   0   0   0
3    7.5   3   2   3   1   7   0   7   3   4   6   1   1
4    8.0   7   9   7   3  12   2   9   4   7   5   2   6
5    8.5  12  12   8   8  15   9  17  17   6   9  10   6
6    9.0  17  13  13  11  21  22  25  30  26  25  13  10
7    9.5  19  25  27  24  26  33  25  47  31  44  37  26
8   10.0  17  26  26  19  16  31  25  24  23  31  15  20
9   10.5  13  16  22  14  28  19  18  15  19  21  16  10
10  11.0   5  16  13  10  10  11  15   8   9   7   6   7
11  11.5   4   3   6   3   3   5   6   4   5  12  13   5
12  12.0   3   0   0   4   4   4   3  12   4   9   2   1
13  13.0   1   1   2   0   3   2   1   0   0   4   3   2
14  14.0   2   6   3   3   5   3   2   1   0   1   2   1
15  15.0   0   0   0   1   1   0   4   0   0   0   0   2
16  16.0   0   0   0   0   0   0   0   0   0   0   0   0

In [39]:
usa15

      US   1   2   3   4   5   6   7   8   9  10  11  12
0    6.0   0   0   0   0   3   1   1   3   5   4   0   0
1    6.5   4   1   0   1   0   0   2   3   0   1   3   3
2    7.0   0   0   0   0   1   2   1   0   1   2   2   3
3    7.5   0   1   2   1   0   0   3   2   3   2   2   2
4    8.0   5   3   1   0   6   6   4   0   5   6   3   3
5    8.5   4   5   3   1   2  11   6   6   4  12   4   2
6    9.0  10  14   7   9  17  16  20  21  13  17  10  12
7    9.5  18  16  23  15  16  16  19  26  25  17  35  24
8   10.0   8  13  13  15   7  20  22  18  22  15  11  14
9   10.5   7  13   8   8  15  10  16   8  16  16  17  14
10  11.0   5   5   4   7   5   5   4   6   3   5   5  10
11  11.5   3   3   2   3   6   9   6   6   3   8   3   7
12  12.0   1   0   0   3   1   4   1   2   4   3   6   3
13  13.0   0   0   1   0   1   3   1   0   0   3   0   1
14  14.0   1   2   1   2   1   0   3   3   0   1   2   2
15  15.0   0   0   0   0   1   0   0   1   1   0   1   1
16  16.0   0   0   0   0   0   0   0   0   0   0   0   0

In [40]:
data = usa15.copy()

col_list = data.columns
month = int(13)
for col in col_list:
    if (col != 'US'):
        data[str(month)] = usa16[col]
        month += 1

data

,US,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,6.0,0,0,0,0,3,1,1,3,5,...,3,1,3,3,3,4,3,7,3,0
1,6.5,4,1,0,1,0,0,2,3,0,...,0,1,0,0,1,7,2,1,2,1
2,7.0,0,0,0,0,1,2,1,0,1,...,1,0,6,4,4,2,3,0,0,0
3,7.5,0,1,2,1,0,0,3,2,3,...,3,1,7,0,7,3,4,6,1,1
4,8.0,5,3,1,0,6,6,4,0,5,...,7,3,12,2,9,4,7,5,2,6
5,8.5,4,5,3,1,2,11,6,6,4,...,8,8,15,9,17,17,6,9,10,6
6,9.0,10,14,7,9,17,16,20,21,13,...,13,11,21,22,25,30,26,25,13,10
7,9.5,18,16,23,15,16,16,19,26,25,...,27,24,26,33,25,47,31,44,37,26
8,10.0,8,13,13,15,7,20,22,18,22,...,26,19,16,31,25,24,23,31,15,20
9,10.5,7,13,8,8,15,10,16,8,16,...,22,14,28,19,18,15,19,21,16,10
10,11.0,5,5,4,7,5,5,4,6,3,...,13,10,10,11,15,8,9,7,6,7
11,11.5,3,3,2,3,6,9,6,6,3,...,6,3,3,5,6,4,5,12,13,5
12,12.0,1,0,0,3,1,4,1,2,4,...,0,4,4,4,3,12,4,9,2,1
13,13.0,0,0,1,0,1,3,1,0,0,...,2,0,3,2,1,0,0,4,3,2
14,14.0,1,2,1,2,1,0,3,3,0,...,3,3,5,3,2,1,0,1,2,1
15,15.0,0,0,0,0,1,0,0,1,1,...,0,1,1,0,4,0,0,0,0,2
16,16.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# compute the mean sales for each shoe size

data['Mean_1516'] = data.iloc[:, 1:25].mean(axis=1)
data

,US,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,Mean_1516
0,6.0,0,0,0,0,3,1,1,3,5,...,1,3,3,3,4,3,7,3,0,2.166667
1,6.5,4,1,0,1,0,0,2,3,0,...,1,0,0,1,7,2,1,2,1,1.583333
2,7.0,0,0,0,0,1,2,1,0,1,...,0,6,4,4,2,3,0,0,0,1.333333
3,7.5,0,1,2,1,0,0,3,2,3,...,1,7,0,7,3,4,6,1,1,2.333333
4,8.0,5,3,1,0,6,6,4,0,5,...,3,12,2,9,4,7,5,2,6,4.791667
5,8.5,4,5,3,1,2,11,6,6,4,...,8,15,9,17,17,6,9,10,6,7.875000
6,9.0,10,14,7,9,17,16,20,21,13,...,11,21,22,25,30,26,25,13,10,16.333333
7,9.5,18,16,23,15,16,16,19,26,25,...,24,26,33,25,47,31,44,37,26,25.583333
8,10.0,8,13,13,15,7,20,22,18,22,...,19,16,31,25,24,23,31,15,20,18.791667
9,10.5,7,13,8,8,15,10,16,8,16,...,14,28,19,18,15,19,21,16,10,14.958333
10,11.0,5,5,4,7,5,5,4,6,3,...,10,10,11,15,8,9,7,6,7,7.541667
11,11.5,3,3,2,3,6,9,6,6,3,...,3,3,5,6,4,5,12,13,5,5.333333
12,12.0,1,0,0,3,1,4,1,2,4,...,4,4,4,3,12,4,9,2,1,3.083333
13,13.0,0,0,1,0,1,3,1,0,0,...,0,3,2,1,0,0,4,3,2,1.208333
14,14.0,1,2,1,2,1,0,3,3,0,...,3,5,3,2,1,0,1,2,1,1.958333
15,15.0,0,0,0,0,1,0,0,1,1,...,1,1,0,4,0,0,0,0,2,0.541667
16,16.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.000000

In [51]:
from math import sqrt

# determine the sample size
n = 24

# determine the standard deviation by row
data['StDev'] = data.iloc[:, 1:25].std(axis=1)

# compute the standard error:  s / sqrt(n)
data['SE'] = data['StDev'] / sqrt(n)

# determine the t-statistic 
tstat = 2.074

# compute the margin of error
data['ME'] = tstat * data['SE']

# compute the 95% CI for the 2015-16 data
data['CI_start'] = data['Mean_1516'] - data['ME']
data['CI_end'] = data['Mean_1516'] + data['ME']


data

,US,1,2,3,4,5,6,7,8,9,...,21,22,23,24,Mean_1516,StDev,SE,ME,CI_start,CI_end
0,6.0,0,0,0,0,3,1,1,3,5,...,3,7,3,0,2.166667,1.926174,0.393179,0.815452,1.351214,2.982119
1,6.5,4,1,0,1,0,0,2,3,0,...,2,1,2,1,1.583333,1.665942,0.340059,0.705282,0.878051,2.288616
2,7.0,0,0,0,0,1,2,1,0,1,...,3,0,0,0,1.333333,1.659404,0.338725,0.702515,0.630819,2.035848
3,7.5,0,1,2,1,0,0,3,2,3,...,4,6,1,1,2.333333,2.014441,0.411196,0.852820,1.480513,3.186154
4,8.0,5,3,1,0,6,6,4,0,5,...,7,5,2,6,4.791667,2.933749,0.598849,1.242013,3.549654,6.033680
5,8.5,4,5,3,1,2,11,6,6,4,...,6,9,10,6,7.875000,4.628010,0.944689,1.959284,5.915716,9.834284
6,9.0,10,14,7,9,17,16,20,21,13,...,26,25,13,10,16.333333,6.183194,1.262139,2.617677,13.715657,18.951010
7,9.5,18,16,23,15,16,16,19,26,25,...,31,44,37,26,25.583333,8.652301,1.766144,3.662982,21.920351,29.246315
8,10.0,8,13,13,15,7,20,22,18,22,...,23,31,15,20,18.791667,6.494005,1.325583,2.749260,16.042407,21.540926
9,10.5,7,13,8,8,15,10,16,8,16,...,19,21,16,10,14.958333,4.999819,1.020584,2.116691,12.841643,17.075024
10,11.0,5,5,4,7,5,5,4,6,3,...,9,7,6,7,7.541667,3.526042,0.719750,1.492762,6.048905,9.034429
11,11.5,3,3,2,3,6,9,6,6,3,...,5,12,13,5,5.333333,2.853932,0.582556,1.208222,4.125111,6.541555
12,12.0,1,0,0,3,1,4,1,2,4,...,4,9,2,1,3.083333,2.842483,0.580219,1.203375,1.879958,4.286708
13,13.0,0,0,1,0,1,3,1,0,0,...,0,4,3,2,1.208333,1.250362,0.255229,0.529345,0.678988,1.737679
14,14.0,1,2,1,2,1,0,3,3,0,...,0,1,2,1,1.958333,1.458980,0.297813,0.617664,1.340669,2.575998
15,15.0,0,0,0,0,1,0,0,1,1,...,0,0,0,2,0.541667,0.931533,0.190148,0.394368,0.147299,0.936034
16,16.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [54]:
# round the upper limit of the CI to determine how many pairs of shoes we should order
data['Number_Pairs'] = data['CI_end'].round(0).astype(int)
data

,US,1,2,3,4,5,6,7,8,9,...,22,23,24,Mean_1516,StDev,SE,ME,CI_start,CI_end,Number_Pairs
0,6.0,0,0,0,0,3,1,1,3,5,...,7,3,0,2.166667,1.926174,0.393179,0.815452,1.351214,2.982119,3
1,6.5,4,1,0,1,0,0,2,3,0,...,1,2,1,1.583333,1.665942,0.340059,0.705282,0.878051,2.288616,2
2,7.0,0,0,0,0,1,2,1,0,1,...,0,0,0,1.333333,1.659404,0.338725,0.702515,0.630819,2.035848,2
3,7.5,0,1,2,1,0,0,3,2,3,...,6,1,1,2.333333,2.014441,0.411196,0.852820,1.480513,3.186154,3
4,8.0,5,3,1,0,6,6,4,0,5,...,5,2,6,4.791667,2.933749,0.598849,1.242013,3.549654,6.033680,6
5,8.5,4,5,3,1,2,11,6,6,4,...,9,10,6,7.875000,4.628010,0.944689,1.959284,5.915716,9.834284,10
6,9.0,10,14,7,9,17,16,20,21,13,...,25,13,10,16.333333,6.183194,1.262139,2.617677,13.715657,18.951010,19
7,9.5,18,16,23,15,16,16,19,26,25,...,44,37,26,25.583333,8.652301,1.766144,3.662982,21.920351,29.246315,29
8,10.0,8,13,13,15,7,20,22,18,22,...,31,15,20,18.791667,6.494005,1.325583,2.749260,16.042407,21.540926,22
9,10.5,7,13,8,8,15,10,16,8,16,...,21,16,10,14.958333,4.999819,1.020584,2.116691,12.841643,17.075024,17
10,11.0,5,5,4,7,5,5,4,6,3,...,7,6,7,7.541667,3.526042,0.719750,1.492762,6.048905,9.034429,9
11,11.5,3,3,2,3,6,9,6,6,3,...,12,13,5,5.333333,2.853932,0.582556,1.208222,4.125111,6.541555,7
12,12.0,1,0,0,3,1,4,1,2,4,...,9,2,1,3.083333,2.842483,0.580219,1.203375,1.879958,4.286708,4
13,13.0,0,0,1,0,1,3,1,0,0,...,4,3,2,1.208333,1.250362,0.255229,0.529345,0.678988,1.737679,2
14,14.0,1,2,1,2,1,0,3,3,0,...,1,2,1,1.958333,1.458980,0.297813,0.617664,1.340669,2.575998,3
15,15.0,0,0,0,0,1,0,0,1,1,...,0,0,2,0.541667,0.931533,0.190148,0.394368,0.147299,0.936034,1
16,16.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0